server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://192.168.20.174::11003/law_enforcement_pollution_source_archives?useUnicode=true&characterEncoding=utf-8&autoReconnect=true&autoReconnectForPools=true&failOverReadOnly=false&useSSL=false&tinyInt1isBit=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: zhifa_dev
    password: zdht.zhifa#2022


generator:
  parent: "com.xx.xxx"
  entity: "entity"